config/routes.rb
Rails.application.routes.draw do
 
root 'home#index'

devise_for :users

devise_scope :user do
	get '/signin', to: 'devise/sessions#new', as: 'signin'
	get '/signup', to: 'devise/registrations#new', as: 'signup'
end

resources :users do
	resources :posts
end

get 'posts/filter/:scope', to: 'posts#index', as: :filtered_posts

resources :posts do
		resources :replies
end 

resources :albums 


end

app/models/post.rb
class Post < ActiveRecord::Base

belongs_to :user
has_many :replies

default_scope -> { order('created_at desc') }
validates :user_id, presence: true
# Disabled the following to enable users to upload image without content
# validates :content, presence: true

has_attached_file :image, 
	:styles => { large: "600x600>", medium: "300x300>", thumb: "150x150>" },
	:path => ":rails_root/public/system/image/:style/:hash.:extension",
	:url => "/system/image/:style/:hash.:extension",
  :hash_secret => "longSecretString" 

  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/

scope :has_photos, -> { where('image_file_name IS NOT NULL').order(:created_at) }
scope :has_link, -> { where('link IS NOT NULL').order(:created_at) } 

accepts_nested_attributes_for :replies

end

app/models/reply.rb
class Reply < ActiveRecord::Base
  belongs_to :post
  belongs_to :user

  validates :post_id, presence: true
  validates :user_id, presence: true
	validates :content, presence: true

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

has_many :posts, dependent: :destroy
has_many :replies, dependent: :destroy

 end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController

def index
	@posts = Post.all
end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
  	devise_parameter_sanitizer.for(:sign_up) << :first_name
  	devise_parameter_sanitizer.for(:sign_up) << :last_name
  	devise_parameter_sanitizer.for(:account_update) << :first_name
  	devise_parameter_sanitizer.for(:account_update) << :last_name
	end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
before_action :require_signin
before_action :set_post, except: [:index, :new, :create]


def index
	case params[:scope]
		when "has_photos"
			@posts = Post.has_photos
		when "has_link"
			@posts = Post.has_link
		else
			@posts = Post.paginate(:page => params[:page], :per_page => 10)
	end

	@post = current_user.posts.build
	@new_reply = @post.replies.build
end


def create
	@post = current_user.posts.build(post_params)
	
	if @post.save
		redirect_to posts_path, notice: "Post created." 
	else
		render :new	
	end
end

def edit
end

def update
	if @post.update(post_params)
		redirect_to posts_path, notice: "Successfully edited!"
	else
		render :edit
	end
end

def destroy
	@post.destroy
	redirect_to posts_path
	notice = "Successfully deleted!"
end

private
	
	def post_params
		params.require(:post).permit(:title, :content, :link, :image)
	end

	def set_post
		@post = Post.find(params[:id])
	end


	def require_signin
		redirect_to root_url unless user_signed_in?
	end

end

app/controllers/replies_controller.rb
class RepliesController < ApplicationController
before_action :set_post

def index
	
end

def new
	
end

def create
#	post = Post.find(params[:post_id])
	@new_reply = @post.replies.build(reply_params)
	@new_reply.user = current_user
	
	respond_to do |format|
		if @new_reply.save
			format.html { redirect_to posts_path }
			format.json { render json: @new_reply, status: :created, location: @new_reply }
			format.js
		else
			format.html { render :new }
			format.json { render json: @new_reply.errors, status: :unprecessable_entity }
			format.js
		end
	end
end

def destroy
	@new_reply.destroy
	redirect_to posts_path
	notice = "Successfully deleted!"
end


private

	def reply_params
		params.require(:reply).permit(:content, :user_id, :post_id)
	end

	def set_post
		@post = Post.find(params[:post_id])
	end

end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

 	def gravatar_url(user)
    gravatar_id = Digest::MD5::hexdigest(user.email).downcase
    "http://gravatar.com/avatar/#{gravatar_id}.png"
  end

# check if the given url has http protocol and if not, append it  
  def url_with_protocol(url)
    /^http/i.match(url) ? url : "http://#{url}"
  end


end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/replies_helper.rb
module RepliesHelper
end

app/views/albums/index.html.erb
<div class="col-md-12">

<h3>Albums Index</h3>

<div class="row">
<% @posts.each do |post| %>
	<% if post.image.exists? %>		
		<div class="col-xs-6 col-md-3">
			<div class="thumbnail">
				<a href="#" data-toggle="modal", data-target="#imageModal-<%= post.id %>">
					<%= image_tag post.image.url(:medium), data: { src: "holder.js/300x300" } %>
				</a>
				<div class="caption">
	        	<p class="muted"><%= time_ago_in_words(post.created_at) %> ago</p>
				</div>
			</div>
			

		<!-- imageModal -->
		<div class="modal fade" id="imageModal-<%= post.id %>" tabindex="-1" role="dialog" aria-labelledby="imageModalLabel" aria-hidden="true">
		  <div class="modal-dialog">
		    <div class="modal-content">
		      <div class="modal-header">
		        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
		        <h4 class="modal-title" id="imageModalLabel"><%= image_tag(gravatar_url(post.user), width: 43, class: "img-circle") %> <%= post.user.first_name %></h4>
		      </div>
		      <div class="modal-body">
		        <%= image_tag post.image.url(:large) %>
		      </div>
		      <div class="modal-footer">
						<p>Posted by <%= post.user.first_name %> <%= time_ago_in_words(post.created_at) %> ago
      		</div>
		    </div>
		  </div>
		</div>
		<!-- end imageModal -->

	</div> <!-- end col-xs-6 col-md-3 -->
<% end %>
<% end %>
</div> <!-- end row -->



</div>

app/views/home/index.html.erb
<h1>Welcome to Coupley</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Coupley</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<!-- Fixed navbar -->
    <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <%= link_to 'Coupley', root_path, class: 'navbar-brand' %>
        </div>
        <div class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li><%= link_to 'Stream', posts_path %></li>
            <li><%= link_to 'Albums', albums_path %></li>
            
            <% if current_user.try(:admin?) %>
              <li><%= link_to 'Admin' %></li>
            <% end %>
          </ul>
            
          <ul class="nav navbar-nav navbar-right">
          <% if user_signed_in? %>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                <%= image_tag(gravatar_url(current_user), width: 20, class: "img-circle") %>
                <%= current_user.first_name %> <span class="caret"></span>
              </a>
              <ul class="dropdown-menu" role="menu">
                <li><%= link_to 'Account Settings', edit_user_registration_path %></li>
                <li class="divider"></li>
                <li><%= link_to 'Sign Out', destroy_user_session_path, method: :delete %></li>
              </ul>
            </li>
           <% else %>
           	<li><%= link_to 'Sign In', signin_path %></li>
           	<li><%= link_to 'Sign Up', signup_path %></li>
           <% end %>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </div>

<div class="container">
	
	<% if notice %>
  	<p class="alert alert-success"><%= notice %></p>
	<% end %>
	<% if alert %>
  	<p class="alert alert-danger"><%= alert %></p>
	<% end %>
	
	<%= yield %>

</div>


</body>
</html>

app/views/posts/_form.html.erb
<div id="post-form">
<script src="//cdn.ckeditor.com/4.4.4/basic/ckeditor.js"></script>

<%= form_for @post, :html => { :multipart => true } do |f| %>
<form class="form-horizontal" role="form">

<ul class="media-list">
	<li class="media">
	    <a class="pull-left" href="#">
	      <%= image_tag(gravatar_url(current_user), width: 43, class: "img-circle") %>
	    </a>
	    <div class="media-body">
				<div class="form-group">
					<div class="input-group">
						<%= f.text_field :title, size: 120, placeholder: "제목 (optional)", class: 'form-control' %>
					</div>
					<div class="input-group">
						<%= f.text_area :content, rows: 5, cols: 103, placeholder: "내용", id:"ckeditor"%>
					</div>
				
				</div>

				<div class="btn-group">
					<%= f.submit value: "Publish", class: "btn btn-lg btn-primary" %>
				</div>
			</div>
	</li>
</ul>

</form>
<% end %>
</div>

app/views/posts/_form_link.html.erb
<%= form_for @post, :html => { :multipart => true } do |f| %>
<form class="form-horizontal" role="form">

<ul class="media-list">
	<li class="media">
	    <a class="pull-left" href="#">
	      <%= image_tag(gravatar_url(current_user), width: 43, class: "img-circle") %>
	    </a>
	    <div class="media-body">
				<div class="form-group">
					<div class="input-group">
						<%= f.text_field :link, size: 120, placeholder: "링크", class: 'form-control' %>
					</div>
					<div class="input-group">
						<%= f.text_area :content, rows: 5, cols: 130, placeholder: "내용 (optional)", class: 'form-control' %>
					</div>
				</div>

				<div class="btn-group">
					<%= f.submit value: "Publish", class: "btn btn-lg btn-primary" %>
				</div>
			</div>
	</li>
</ul>

</form>
<% end %>

app/views/posts/_form_photo.html.erb
<%= form_for @post, :html => { :multipart => true } do |f| %>
<form class="form-horizontal" role="form">

<ul class="media-list">
	<li class="media">
	    <a class="pull-left" href="#">
	      <%= image_tag(gravatar_url(current_user), width: 43, class: "img-circle") %>
	    </a>
	    <div class="media-body">
				<div class="form-group">
					<div class="input-group">
						<%= f.file_field :image %>
					</div>
				</div>

				<div class="btn-group">
					<%= f.submit value: "Publish", class: "btn btn-lg btn-primary" %>
				</div>
			</div>
	</li>
</ul>

</form>
<% end %>

app/views/posts/_posts.html.erb
<% @posts.each do |post| %>

<li class="media">
  <a class="pull-left" href="#">
    <%= image_tag(gravatar_url(post.user), width: 43, class: "img-circle") %>
  </a>
  <div class="media-body">
    <!-- Display link if any -->
    <% if post.link %>
      <h4 class="media-heading"><%= link_to post.link, url_with_protocol(post.link), target: '_blank' %></h4>
    <% end %>
    <!-- Display title if any -->
    <% if post.title %>
      <h4 class="media-heading"><%= post.title %></h4>
    <% end %>
    <%= raw(post.content) %> 
    <!-- Display image if any -->
    <% if post.image.exists? %>
      <div class="post-image">
        <%= image_tag post.image.url(:large) %>
      </div>
    <% end %>
    <p class="muted"><%= time_ago_in_words(post.created_at) %> ago</p>

  <!-- Display each post's replies -->
  <%= render partial: 'replies/reply', locals: { post: post } unless post.replies.blank? %>
  <!-- Display form for reply -->
  <%= render partial: 'replies/form', locals: { post: post } if current_user  %> 

  </div>

  <!-- Action console to enable post.user to edit and delete her post -->
  <% if current_user == post.user %>
    <div class="action-console">
    <%= link_to 'Edit', edit_post_path(post) %> | 
    <%= link_to 'Delete', post_path(post), method: :delete %>
    </div>
  <% end %>
  <hr></hr>
</li>

<% end %>

app/views/posts/create.js.erb
$("<%= j (render @post) %>").prependTo("#posts-list");

app/views/posts/edit.html.erb
<h4>Edit Post</h4>
<%= render 'form' %>

app/views/posts/index.html.erb
<div class="col-md-9">

<div class="select-post-type">
  <ul class="nav nav-tabs" role="tablist">
    <li><button type="button" class="btn btn-danger" data-toggle="tab" data-target="#text">Text</button></li>
    <li><button type="button" class="btn btn-danger" data-toggle="tab" data-target="#photo">Photo</button></li>
    <li><button type="button" class="btn btn-danger" data-toggle="tab" data-target="#link">Link</button></li>
  </ul>

  <div class="tab-content">
    <div class="tab-pane" id="text">
      <div><%= render 'form' %></div>
    </div>
    <div class="tab-pane" id="photo">
      <div><%= render 'form_photo' %></div>
    </div>
    <div class="tab-pane" id="link">
      <div><%= render 'form_link' %></div>
    </div>
  </div>
</div>

<hr>

<ul class="media-list" id="posts-list">
  <!-- Display each post -->
  <%= render 'posts' %>
</ul>

<%= will_paginate @posts %>

</div> <!-- end col-md-9 -->

<div class="col-md-3">
  <ul>
    <li><%= link_to 'has_photos', filtered_posts_path(:has_photos) %></li>
    <li><%= link_to 'has_link', filtered_posts_path(:has_link) %></li>
  </ul>

</div> <!-- end col-md-3 -->

app/views/posts/new.html.erb
<h4>Post New Content</h4>
	<%= render 'form' %>

app/views/posts/show.html.erb
<ul class="posts">

		<li>
			<span class="author">
				<%= @post.user.first_name %>
			</span>
			<span class="timestamp">
				<%= time_ago_in_words(@post.created_at) %> ago
			</span>
			<span class="content">
				<%= @post.content %> 
			</span>
			
			<% if @post.replies.any? %>
			<div>
				<ul>	
				<% @replies.each do |reply| %>
					<li>
						<%= reply.content %> by <%= reply.user.first_name %>
						<span><%= time_ago_in_words(reply.created_at) %> ago</span>
						<div><%= reply.post_id %></div>
					</li>
				<% end %>
				</ul>
			</div>
			<% end %>

			

			<span class="action-console">
				<%= link_to 'Reply', new_post_reply_path(@post) %> 
			</span>

			<% if current_user == @post.user %>
				<span class="action-console">
				|	<%= link_to 'Edit', edit_post_path(@post) %> | <%= link_to 'Delete', post_path(@post), method: :delete, data: { confirm: "Are you sure?" } %>
				</span>
			<% end %>

		</li>
	
	</ul>

app/views/replies/_form.html.erb
<%= form_for @new_reply, url: post_replies_path(post), html: { method: :post } do |f| %>
<form class="form-horizontal" role="form">
	<div class="media" id="replies-list">
	  <a class="pull-left" href="#">
	    <%= image_tag(gravatar_url(current_user), width: 38, class: "img-circle") %>
	  </a>
	  <div class="media-body">
	    <div class="form-group">
	    	<div class="input-group">
			    <%= f.text_field :content, size: 70 %>
			    <%= f.submit value: 'Reply', class: 'btn btn-default' %>
		    </div>
	    </div>
	  </div>
	</div>
</form>
<% end %>

app/views/replies/_reply.html.erb
<!-- Display replies if any -->
      
        <% post.replies.each do |reply| %>
          <div class="media" id="replies-list">
            <a class="pull-left" href="#">
              <%= image_tag(gravatar_url(reply.user), width: 38, class: "img-circle") %>
            </a>
            <div class="media-body">
              <%= raw(reply.content) %>
              <p class="muted"><%= time_ago_in_words(reply.created_at) %> ago</p>
            </div>
          </div>
        <% end %>
      

app/views/replies/create.js.erb
$("<%= j (render @new_reply) %>").appendTo("#replies-list");